### ISSUE TITLE
Possible direction error

### ISSUE THREAD

**Issue by mat-gys** [BigBang1112/gbx-net#106]
When parsing track "Somewhere I belong" (track id 11817), you get that the second block is a "StadiumRoadTiltCornerDownLeft" facing North. As you can see in the image, if the first block is facing East (which it is, and is correctly classified by the parser), then the second block should be facing South (rotated twice), no?
![image](https://github.com/BigBang1112/gbx-net/assets/88738375/01a3e45a-40ea-4a79-827c-782458df00f5)

Code used:
```c#
using GBX.NET;
using GBX.NET.Engines.Game;
using GBX.NET.LZO;
using System.IO;
using System.Text;

Gbx.LZO = new MiniLZO();



var gbx = Gbx.Parse<CGameCtnChallenge>("path/_Somewhere I belong.Challenge.Gbx");
var map = gbx.Node; // See Clarity section for more info

int iterationCount = 0;

foreach (var block in map.Blocks)
{
    Console.WriteLine($"Name: {block.Name}");
    Console.WriteLine($"Direction: {block.Direction}");
    Console.WriteLine($"Coordinates: ({block.Coord.X}, {block.Coord.Y}, {block.Coord.Z})");
    Console.WriteLine($"Flags: {block.Flags}");
    Console.WriteLine($"Variant: {block.Variant}");
    Console.WriteLine($"Pitch, Yaw, Roll: {block.PitchYawRoll}");

    Console.WriteLine(); // Add a blank line for readability
    
    iterationCount++;

    if (iterationCount >= 3)
    {
        break; // Exit the loop after 3 iterations
    }
}
``` 
Result from code:
![image](https://github.com/BigBang1112/gbx-net/assets/88738375/7aa8b89f-b07e-4704-8d42-c106ff34abfc)

**Comment by BigBang1112** [comment]
I tested this on a fresh map. I know already the initial rotation is North so I first placed a block, then rotated once, placed a block, and so on until I placed all 4 directions. Then I saved the map and check in both GBX.NET 1.2.6 and 2.0.0. Both versions yield the same result:
- StadiumRoadMainFinishLine: North
- StadiumRoadMainFinishLine: East
- StadiumRoadMainFinishLine: South
- StadiumRoadMainFinishLine: West
Which is a clockwise rotation of blocks that the game uses. So there's no bug with the direction itself.

It could be that some of the Nadeo blocks could be unpredictable in how they are facing vs the "direction" in regular sense.

**Comment by mat-gys** [comment]
Ah, yes. I tested it, and it does seem to be that the StadiumRoadTiltCornerDownLeft block is originally "facing south" when rotation is set at 0 (i.e., the "DownLeft" part of the name does not actually indicate that the block is leading you down and west). I hope that explanation made some sense. I'm not sure what the guidelines are; I don't want to open up issues that are actually misunderstanding on my side: is there a place I could ask questions if I find something I think might be wrong?

For example, I see that PitchYawRoll is missing even when rotating the block using TMUnlimiter. But maybe that's not what the attribute is trying to represent.

**Comment by BigBang1112** [comment]
It's fine to put the issues, there are no guidelines because there is still a small amount of them and I can manage it without any guidelines. But in case you want more real-time discussion then there's [GameBox Sandbox](https://discord.gg/tECTQcAWC9), also available through clicking the Chat shield in the README.

`PitchYawRoll` is only available for TM2020 free blocks. I forgot to put the `<summary>` tag on it to explain that. Also, TMUnlimiter specific stuff is still not available, but I'm communicating that up with Tomek and we may have it in a few weeks.
