### ISSUE TITLE
AuthorLogin and AuthorNickname is always null on TMUF/TMNF maps

### ISSUE THREAD

**Issue by ArkadySK** [BigBang1112/gbx-net#111]
I have tried (fully) parsing many *.Challenge.Gbx files from TMUF/TMNF and all of them seem to have missing AuthorLogin and AuthorNickname properties. It worked perfectly well in the prior versions of the GBX.NET.

Both of the properties work perfectly fine on ManiaPlanet or TMNext maps.

**Comment by BigBang1112** [comment]
Fixed, thanks for the report, this was a forgotten part of `CGameCtnChallenge` port. https://github.com/BigBang1112/gbx-net/commit/0dc303b02285c65351a869a8cda55372b6ba3aee
