### ISSUE TITLE
Not converting to .challenge.gbx

### ISSUE THREAD

**Issue by fosterchild1** [BigBang1112/gbx-net#124]
Hi, I was watching [this](https://www.youtube.com/watch?v=hbbIbw4-E_Y) tutorial made by you. I wanted to extract a track from my replay because it got corrupted. I did all the steps in the video, but it doesnt want to export it as a .challenge.gbx!!

# please help!!! 
here are the files:
[lucky #02 wip_fosterchild(00'36''08).Replay.zip](https://github.com/user-attachments/files/17179073/lucky.02.wip_fosterchild.00.36.08.Replay.zip)

**Comment by fosterchild1** [comment]
![image](https://github.com/user-attachments/assets/8319def5-0716-4f44-8630-9c0acfc51a42)

**Comment by fosterchild1** [comment]
here is the corrupted track too.. if you can, try to un-corrupt it.

i wanted to change the times to the ones in the replay because i added the replay to GPS and that makes trackmania unvalidate the track, even if you finished it already. that ended up corrupting it, even after i rolled back my changes :(
[lucky #02 wip.Challenge.zip](https://github.com/user-attachments/files/17179248/lucky.02.wip.Challenge.zip)

**Comment by BigBang1112** [comment]
Just specify the name like `lucky #02.Challenge`. For these simple tasks, I made a side as well which aims to make it simpler: https://io.gbx.tools/extract-map-from-replay

**Comment by fosterchild1** [comment]
thank you so much!!
