### ISSUE TITLE
Unable to parse Trackmania 2020 maps after update because missing parsing support for a new node type

### ISSUE THREAD

**Issue by vjeux** [BigBang1112/gbx-net#41]
Hello!

First of all, thanks so much for building this, I've been using this project to make Trackmania 2020 maps for the shitfest event with great success!

Last Friday there's been an update to the game and opening the maps created by the editor no longer works because it's missing how to parse a new node ID: 0x0338B000.

```
GBX.NET.Exceptions.NodeNotImplementedException: 'Node with ID 0x0338B000 is not implemented. (unknown class)'
```

I'm happy to spend some time trying to figure out how to add support for parsing it but I'm not really sure how to get started. Do you have some recommendation around what to look for / how to get started?

Thanks!

**Comment by BigBang1112** [comment]
Hello, I'll look at this in the evening, thanks for letting me know.

> I'm happy to spend some time trying to figure out how to add support for parsing it but I'm not really sure how to get started. Do you have some recommendation around what to look for / how to get started?

The [Essentials](https://github.com/BigBang1112/gbx-net/wiki/Essentials) page can give you a rough start to the internal side of the project. Other detailed tutorials are still on the way to be made.

Regarding the node itself and how to deal with the `ReadWrite()` method is a task that requires experience of patterns in the chunk structure, or by having an already resolved reverse engineered version of the game (which is not an option in this case as this may be a very recent feature). I can handle this myself all good, shouldn't be difficult.

**Comment by vjeux** [comment]
Sounds good. Good to know that openplanet.dev has a way to get the name and fields out of the node id.

**Comment by BigBang1112** [comment]
> Sounds good. Good to know that openplanet.dev has a way to get the name and fields out of the node id.

The MediaTracker fields are usually hidden from us though xd

This bug is fixed in https://github.com/BigBang1112/gbx-net/commit/ab59cd7318b1fbb6b37fe3f97f0198b49354a295 and will be pushed as 0.15.1 in a few hours.

**Comment by vjeux** [comment]
Thank you, just rebased and it's working again <3
