### ISSUE TITLE
Problems running on linux

### ISSUE THREAD

**Issue by SindreMA** [BigBang1112/gbx-net#51]
I'm trying to implement this into an API. 
I got it working fine in my dev env, but when i moved it over to my server that is running linux , it started crashing.

Here is the error given:

<img width="1556" alt="image" src="https://user-images.githubusercontent.com/29127320/182251874-a5cd09d8-4853-4481-8cc3-9b138cf15fe4.png">

Looks like it have some problems with the decompress lib when running on linux.
At the moment i've solved this by running a windows proxy, but would be great to have fixed one day.

Else great work with this lib, saves me alot of work.

**Comment by BigBang1112** [comment]
Have you used Nuget packages or built it from the solution?

**Comment by BigBang1112** [comment]
Some troubleshooting that comes to my mind:

- If you build the whole solution for it, check that you're correctly targeting the platforms.
- Call this once at the beginning of your program: `GBX.NET.Lzo.SetLzo(typeof(GBX.NET.LZO.MiniLZO));`, to link the library properly on different operating systems.
- If none of these work, try to use GBX.NET 0.15.0 or 0.15.1, the LZO library wasn't specifically built for 0.16.0, but please if possible, use the latest version. If any of them are known to be broken is told in the Nuget version browser.

**Comment by SindreMA** [comment]
> * If you build the whole solution for it, check that you're correctly targeting the platforms.
> * Call this once at the beginning of your program: `GBX.NET.Lzo.SetLzo(typeof(GBX.NET.LZO.MiniLZO));`, to link the library properly on different operating systems.
> * If none of these work, try to use GBX.NET 0.15.0 or 0.15.1, the LZO library wasn't specifically built for 0.16.0, but please if possible, use the latest version. If any of them are known to be broken is told in the Nuget version browser.

Thanks for the answer, 
I've tried all 3 points now, with no luck, got same error code after all changes.
Will just keep using the window proxy for now as i want to move on coding the rest.

Will for sure give it another attempt if you release a automated version

**Comment by BigBang1112** [comment]
Closing as this seems to be a local problem with how the native code is processed on certain machines (possibly different architecture). I've already implemented GBX.NET on my Linux servers successfully with no issues like these.
